[build-system]
requires = ["setuptools>=61.0", "pybind11"]
build-backend = "setuptools.build_meta"

[project]
name = "photoedit"
version = "0.1.0"
description = "Image Editor"
authors = [{name = "Alex T."}]

[tool.setuptools.packages.find]
where = ["backend"]